---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: core-controller
#  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: core-controller
#  namespace: default
rules:
  - apiGroups: [ "" ]
    resources: [  "secrets", "services" ]
    verbs: [ "create", "update", "get", "watch", "list" ]
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: core-controller
#  namespace: default
roleRef:
  kind: ClusterRole
  name: core-controller
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: core-controller
#    namespace: default